cities/urls.py
from django.urls import path
from cities.views import *

urlpatterns = [
    path('', CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='create'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include
from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cities/', include(('cities.urls', 'cities'))),
    path('trains/', include(('trains.urls', 'trains'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
]

routes/models.py
from django.db import models

from cities.models import City


class Route(models.Model):
    name = models.CharField(max_length=50, unique=True,
                            verbose_name='Название маршрута')
    travel_times = models.PositiveSmallIntegerField(
                            verbose_name='Общее время в пути')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  related_name='route_from_city_set',
                                  verbose_name='Из какого города')
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE,
                                related_name='route_to_city_set',
                                verbose_name='В какой город')
    trains = models.ManyToManyField(
        'trains.Train', verbose_name='Список поездов')

    def __str__(self):
        return f'Маршрут {self.name} из города {self.from_city}'

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'
        ordering = ['travel_times']

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'list' as route_list %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Select2  -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light container">
  <a class="navbar-brand" href="{% url 'home' %}">Find Route</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == cities_home_url %} active {% endif %}">
        <a class="nav-link" href="{% url 'cities:home' %}">Города</a>
      </li>
      <li class="nav-item {% if request.path == trains_home_url %} active {% endif %}">
        <a class="nav-link" href="{% url 'trains:home' %}">Поезда</a>
      </li>
      <li class="nav-item {% if request.path == route_list %} active {% endif %}">
        <a class="nav-link" href="{% url 'list' %}">Маршруты</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown
        {% if request.path == cities_create_url or request.path == trains_create_url %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Добавить
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'cities:create' %}">Новый город</a>
          <a class="dropdown-item" href="{% url 'trains:create' %}">Новый поезд</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      {% endif %}
      </li>
      {% if not user.is_authenticated %}
          <li class="nav-item " >
            <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
          </li>
          <li class="nav-item " >
            <a class="nav-link" href="{% url 'accounts:register' %}">Регистрация</a>
          </li>
      {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
          </li>
      {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  </nav>
      <div class="container">
        <div class="row">
          <div class="col-md-8 mx-auto my-4">
            {% if messages %}
              {% for message in messages %}
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>

                  {% else %}
                      <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                  {% endif %}
              {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>
      <div class="container">
        {% block content %}{% endblock %}
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
      $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
      });
    </script>
  </body>

</html>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{ action }}" method="post"> {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> {{ button }} </button>
        </form>
    </div>
</div>